// request
export const MEAL_SCHEDULE_SUCCESS = 'MEAL_SCHEDULE_SUCCESS';
export const MEAL_SCEDULE_FAILURE = 'MEAL_SCHEDULE_FAILURE';
// request
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';
export const UPDATE_MEAL_FAILURE = 'UPDATE_MEAL_FAILURE';
//
export const ADD_MEAL_COUNT = 'ADD_MEAL_COUNT';
