// request
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAILURE = 'SEND_MAIL_FAILURE';
// input
export const EMAIL_BODY_INPUT = 'EMAIL_BODY_INPUT';
export const EMAIL_SUBJECT_INPUT = 'EMAIL_SUBJECT_INPUT';
export const EMAIL_RECIPIENT_INPUT = 'EMAIL_RECIPIENT_INPUT';
export const EMAIL_ATTACHMENT_INPUT = 'EMAIL_ATTACHMENT_INPUT';
// errors
export const CHANGE_ERROR_STATUS = 'CHANGE_ERROR_STATUS';
