// request
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';
// inputs
export const INPUT_FIRST_NAME = 'INPUT_FIRST_NAME';
export const INPUT_SECOND_NAME = 'INPUT_SECOND_NAME';
export const INPUT_POSITION = 'INPUT_POSITION';
export const INPUT_EMPLOYMENT_DATE = 'INPUT_EMPLOYMENT_DATE';
export const INPUT_WORK_DEPARMENT = 'INPUT_WORK_DEPARTMENT';
export const INPUT_ADDRESS = 'INPUT_ADDRESS';
export const INPUT_CITY = 'INPUT_CITY';
export const INPUT_STATE = 'INPUT_STATE';
export const INPUT_SOCIAL_NUMBER = 'INPUT_SOCIAL_NUMBER';
export const INPUT_IDENTITY_CARD = 'INPUT_INDENTITY_CARD';
export const INPUT_TELEPHONE_NUMBER = 'INPUT_TELEPHONE_NUMBER';
export const INPUT_EMAIL_ADDRESS = 'INPUT_EMAIL_ADDRESS';
