// request
export const SEARCH_EMPLOYEE_SUCCESS = 'SEARCH_EMPLOYEE_SUCCESS';
export const SEARCH_EMPLOYEE_FAILURE = 'SEARCH_EMPLOYEE_FAILURE';
// input
export const INPUT_SEARCH_EMPLOYEE = 'INPUT_SEARCH_EMPLOYEE';
