// request
export const UPDATE_SHIFT_SUCCESS = 'UPDATE_SHIFT_SUCCESS';
export const UPDATE_SHIFT_FAILURE = 'UPDATE_SHIFT_FAILURE';
// request
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_FAILURE';
// request switch status
export const SWITCH_SHIFT_SUCCESS = 'SWITCH_SHIFT_SUCCESS';
export const SWITCH_SHIFT_FAILURE = 'SWITCH_SHIFT_FAILURE';
// input
export const INPUT_EMPLOYEE_ID = 'INPUT_EMPLOYEE_ID';
export const INPUT_SHIFT_CODE = 'INPUT_SHIFT_CODE';
export const INPUT_EMPLOYEE_STATUS = 'INPUT_EMPLOYEE_STATUS';
export const INPUT_START_DATE = 'INPUT_START_DATE';
export const INPUT_END_DATE = 'INPUT_END_DATE';
// select
export const SELECT_ONE_SHIFT = 'SELECT_ONE_SHIFT';
// count
export const ADD_MEAL_COUNT = 'ADD_MEAL_COUNT';
// errors
export const CHANGE_ERROR_STATUS = 'CHANGE_ERROR_STATUS';
// check duplicate
export const SHIFT_DUPLICATE_TRUE = 'SHIFT_DUPLICATE_TRUE';
export const SHIFT_DUPLICATE_FALSE = 'SHIFT_DUPLICATE_FALSE';
