// request
export const SUCCESS_UPDATE_CONTRACT = 'SUCCESS_UPDATE_CONTRACT';
export const FAILURE_UPDATE_CONTRACT = 'FAILURE_UPDATE_CONTRACT';
// input
export const UPDATE_CONTRACT_START = 'UPDATE_CONTRACT_START';
export const UPDATE_CONTRACT_END = 'UPDATE_CONTRACT_END';
export const UPDATE_SALARY = 'UPDATE_SALARY';
// select
export const SELECT_ONE_CONTRACT = 'SELECT_ONE_CONTRACT';
// end contract
export const END_CONTRACT_SUCCESS = 'END_CONTRACT_SUCCESS';
export const END_CONTRACT_FAILURE = 'END_CONTRACT_FAILURE';
// errors
export const CHANGE_ERROR_STATUS = 'CHANGE_ERROR_STATUS';
