// request
export const SUCCESS_UPDATE_CONTRACT = 'SUCCESS_UPDATE_CONTRACT';
export const FAILURE_UPDATE_CONTRACT = 'FAILURE_UPDATE_CONTRACT';
// input
export const UPDATE_CONTRACT_START = 'UPDATE_CONTRACT_START';
export const UPDATE_CONTRACT_END = 'UPDATE_CONTRACT_END';
export const UPDATE_ACTIVE_CONTRACT = 'UPDATE_ACTIVE_CONTRACT';
